version: '3.8'

services:
    gateway:
        container_name: teledocy-gateway-1
        build: ./gateway
        ports:
            - '4000:4000'
        networks:
            - app-network

    frontend:
        container_name: teledocy-frontend-1
        build: ./frontend
        ports:
            - '5173:5173'
        depends_on:
            - gateway
        environment:
            - VITE_API_URL=http://localhost:4000
        networks:
            - app-network
    #FOR SQL
    mysql:
        image: mysql:8.0
        restart: always
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_DATABASE: consultationHistory
        ports:
            - "3307:3306"
        volumes:
            - mysql_data:/var/lib/mysql
            - ./microservices/consultation_history/consultation_history.sql:/docker-entrypoint-initdb.d/consultation_history.sql
            - ./microservices/medicine_inventory/medicine_inventory.sql:/docker-entrypoint-initdb.d/medicine_inventory.sql
            - ./microservices/delivery_detail/delivery_detail.sql:/docker-entrypoint-initdb.d/delivery_detail.sql
            - ./microservices/notification/notification.sql:/docker-entrypoint-initdb.d/notification.sql

    consultationhistory:
        build:
            context: .
            dockerfile: ./microservices/consultation_history/consultation_history.Dockerfile  
        depends_on:
            - mysql
        ports:
            - "5000:5000"
        environment:
            - DB_URI=mysql+mysqlconnector://root:root@mysql:3306/consultationHistory
    
    medicine_inventory:
        build:
            context: .
            dockerfile: ./microservices/medicine_inventory/medicine_inventory.Dockerfile  
        depends_on:
            - mysql
        ports:
            - "5100:5000"
        environment:
            - DB_URI=mysql+mysqlconnector://root:root@mysql:3306/medicineInventory

    delivery_detail:
        build:
            context: .
            dockerfile: ./microservices/delivery_detail/delivery_detail.Dockerfile  
        depends_on:
            - mysql
        ports:
            - "5200:5000"
        environment:
            - DB_URI=mysql+mysqlconnector://root:root@mysql:3306/deliveryDetail
    
    notification:
        build:
            context: .
            dockerfile: ./microservices/notification/notification.Dockerfile  
        depends_on:
            - mysql
        ports:
            - "5300:5000"
        environment:
            - DB_URI=mysql+mysqlconnector://root:root@mysql:3306/notification

<<<<<<< HEAD
=======
    order:
        build:
            context: .
            dockerfile: ./microservices/order_service/order_service.Dockerfile  
        depends_on:
            - mysql
        ports:
            - "5600:5000"
        environment:
            - DB_URI=mysql+mysqlconnector://root:root@mysql:3306/order

    postgres:
        image: postgres:17
        restart: always
        environment:
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: postgres
            POSTGRES_DB: schedule
        ports:
            - "5432:5432"
        volumes:
            - postgres_data:/var/lib/postgresql/data
            - ./microservices/schedule/schedule.sql:/docker-entrypoint-initdb.d/schedule.sql
            - ./microservices/doctor/doctor.sql:/docker-entrypoint-initdb.d/doctor.sql

        networks:
            - app-network

    schedule:
        build:
            context: .
            dockerfile: ./microservices/schedule/schedule.Dockerfile
        depends_on:
            - postgres
        ports:
            - "5400:5000"
        environment:
            - DB_URI=postgresql+psycopg2://postgres:postgres@postgres:5432/schedule
        networks:
            - app-network

    doctor:
        build:
            context: .
            dockerfile: ./microservices/doctor/doctor.Dockerfile
        depends_on:
            - postgres
        ports:
            - "5500:5000"
        environment:
            - DB_URI=postgresql+psycopg2://postgres:postgres@postgres:5432/doctor
        networks:
            - app-network
    
>>>>>>> belle-doctor
volumes:
  mysql_data:

networks:
    app-network:
        driver: bridge
