version: '3.8'

services:
    gateway:
        container_name: teledocy-gateway-1
        build: ./gateway
        ports:
            - '4000:4000'
        networks:
            - app-network

    frontend:
        container_name: teledocy-frontend-1
        build: ./frontend
        ports:
            - '5173:5173'
        depends_on:
            - gateway
        environment:
            - VITE_API_URL=http://localhost:4000
        networks:
            - app-network
    #FOR SQL
    mysql:
        image: mysql:8.0
        restart: always
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_DATABASE: consultationHistory
        ports:
            - "3307:3306"
        volumes:
            - mysql_data:/var/lib/mysql
            - ./databases/consultationhistory.sql:/docker-entrypoint-initdb.d/consultationhistory.sql
            - ./databases/medicine_inventory.sql:/docker-entrypoint-initdb.d/medicine_inventory.sql
            - ./databases/delivery_detail.sql:/docker-entrypoint-initdb.d/delivery_detail.sql
            - ./databases/notification.sql:/docker-entrypoint-initdb.d/notification.sql

    consultationhistory:
        build:
            context: .
            dockerfile: ./consultationhistory.Dockerfile  
        depends_on:
            - mysql
        ports:
            - "5000:5000"
        environment:
            - DB_URI=mysql+mysqlconnector://root:root@mysql:3306/consultationHistory
    
    medicine_inventory:
        build:
            context: .
            dockerfile: ./medicine_inventory.Dockerfile  
        depends_on:
            - mysql
        ports:
            - "5100:5000"
        environment:
            - DB_URI=mysql+mysqlconnector://root:root@mysql:3306/medicineInventory

    delivery_detail:
        build:
            context: .
            dockerfile: ./medicine_inventory.Dockerfile  
        depends_on:
            - mysql
        ports:
            - "5200:5000"
        environment:
            - DB_URI=mysql+mysqlconnector://root:root@mysql:3306/delivery_detail
    
    notification:
        build:
            context: .
            dockerfile: ./notification.Dockerfile  
        depends_on:
            - mysql
        ports:
            - "5300:5000"
        environment:
            - DB_URI=mysql+mysqlconnector://root:root@mysql:3306/notification

    doctor:
        build:
            context: .
            dockerfile: ./doctor.Dockerfile  
        depends_on:
            - mysql
        ports:
            - "5300:5000"
        environment:
            - 'DB_URI=postgresql+psycopg2://postgres:postgres@localhost:5432/doctor'

volumes:
  mysql_data:

networks:
    app-network:
        driver: bridge
