DROP DATABASE IF EXISTS payment;
CREATE DATABASE IF NOT EXISTS payment;
USE payment;

CREATE TABLE IF NOT EXISTS payment (
    paymentID INT AUTO_INCREMENT PRIMARY KEY,
    uuid VARCHAR(36) NOT NULL,
    amount DECIMAL(10,2) NOT NULL,
    datetime DATETIME DEFAULT CURRENT_TIMESTAMP
);

-- Dummy data
INSERT INTO payment (uuid, amount) VALUES
('uuid-1234', 45.50),
('uuid-5678', 80.00);
